### ISSUE TITLE
Missing sound files?

### ISSUE THREAD

**Issue by TaintedMeat** [Sunconure11/dungeon-mobs#44] opened 2020-04-12 23:47 UTC
"[14:48:30] [Client thread/WARN] [net.minecraft.client.audio.SoundHandler]: File dungeonmobs:sounds/g2_l.ogg does not exist, cannot add it to event dungeonmobs:g2_l"

Discovered this line while looking into an "impossible" sound engine critical error that keeps crashing forge.

The full log is too long for pastebin, so I'm just gonna keep it to the sound manager portion. **(the crash happens independently of your and lycanite's mobs, as I have gotten the same result without either enabled.)**
https://pastebin.com/fxVWTFcZ

**Comment by BlackJar72** [comment] 2020-04-13 04:22
I no longer have a copy of the code, but I can tell what the problem is: A block of JSON (sounds.json) code has error.  I has, 

`  "g2_l": {
	"category": "entity",
	"sounds": [
	  {
		"name": "dungeonmobs:g2_l1",
		"stream": true
	  }
	]
  },`

...but it should have...

`  "g2_l": {
	"category": "entity",
	"sounds": [
	  {
		"name": "dungeonmobs:g2_l",
		"stream": true
	  }
	]
  },`

**Comment by BlackJar72** [comment] 2020-04-16 20:07
I don't think this will be fixed -- its not a crash and I've been informed that all development has move on to 1.15.2.

**Closed by BlackJar72** 2020-04-16 20:07 UTC
Labels: bug, wontfix
